services:
  web:
    build: .
    container_name: lasse-melcher-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
