services:
  web:
    build: .
    container_name: lasse-melcher-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web-network

  # SSL certificate generator (for development)
  ssl-generator:
    image: alpine:latest
    container_name: ssl-generator
    volumes:
      - ./ssl:/ssl
    command: >
      sh -c "
        apk add --no-cache openssl &&
        mkdir -p /ssl &&
        if [ ! -f /ssl/cert.pem ]; then
          echo 'Generating self-signed SSL certificate...' &&
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 
            -keyout /ssl/key.pem 
            -out /ssl/cert.pem 
            -subj '/C=DE/ST=Berlin/L=Berlin/O=Lasse Melcher/CN=localhost'
        else
          echo 'SSL certificate already exists.'
        fi
      "
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

volumes:
  ssl-data:
